# https://taskfile.dev

version: '3'

includes:
  common: ../common

dotenv: ['.env', '.secrets', '../.env', '../.secrets']
env:
  APP_VERSION: 2.0.0
  BUILD_DIR: build/libs
  BUILD_SCRIPT: .github/scripts/build-app.sh
  GH_REPO: spring-music
  WORKDIR:
    sh: mktemp -d -p . -t workspace-XXXXXXXXXX
  ARTIFACT_DIR_NAME: "artifacts"
  SCAN_RESULT_DIR_NAME: "scan_results"
  SRC_DIR_NAME: "sourcecode"
  ARTIFACT_DIR: "{{.WORKDIR}}/{{.ARTIFACT_DIR_NAME}}"
  SRC_DIR: "{{.WORKDIR}}/{{.SRC_DIR_NAME}}"
  SCAN_RESULT_DIR: "./{{.SCAN_RESULT_DIR_NAME}}"
  DOCKER_DIR: "{{.SRC_DIR}}/{{.GH_REPO}}"
  DOCKER_BUILD_TYPE: "buildx"
  DOCKER_IMAGE_SCANNER: "trivy"
  DOCKERFILE_SCANNER: "trivy"
  STOP_ON_CRITICAL_VULNS: "false"
  DOCKER_SBOM_GENERATOR: "syft"

tasks:
  build-push-docker-image-amazoncorretto:
    cmds:
      - task: common:build-push-docker-image-java
        vars:
          DOCKER_BUILD_IMAGE: "alpine3.16:openjdk17"
          DOCKER_BUILD_TYPE: "kaniko"
          DOCKER_IMAGE_NAME: "{{.GH_REPO}}"
          DOCKER_IMAGE_TAG: "{{.APP_VERSION}}-amazoncorretto-17-alpine3-15"
          DOCKERFILE_NAME: "Dockerfile.amazoncorretto-17-alpine3-15"
      - defer:
        task: common:cleanup-workdir

  build-push-docker-image-curated-alpine3-16-openjdk17:
    cmds:
      - task: common:build-push-docker-image-java
        vars:
          DOCKER_BUILD_IMAGE: "alpine3.16:openjdk17"
          DOCKER_BUILD_TYPE: "kaniko"
          DOCKER_IMAGE_NAME: "{{.GH_REPO}}"
          DOCKER_IMAGE_TAG: "{{.APP_VERSION}}-curated-alpine3.16-openjdk17"
          DOCKERFILE_NAME: "Dockerfile.curated-alpine3.16-openjdk17"
          DOCKER_IMAGE_SCANNER: "grype"
      - defer:
        task: common:cleanup-workdir

  build-push-docker-image-temurin:
    cmds:
      - task: common:build-push-docker-image-java
        vars:
          DOCKER_BUILD_IMAGE: "ubuntu22.04:openjdk17"
          DOCKER_IMAGE_NAME: "{{.GH_REPO}}"
          DOCKER_IMAGE_TAG: "{{.APP_VERSION}}-eclipse-temurin-17-jre-jammy"
          DOCKERFILE_NAME: "Dockerfile.eclipse-temurin-17-jre-jammy"
          DOCKER_IMAGE_SCANNER: "grype"
          STOP_ON_CRITICAL_VULNS: "true"
      - defer:
        task: common:cleanup-workdir

  build-push-docker-image-distroless:
    cmds:
      - task: common:build-push-docker-image-java
        vars:
          DOCKER_BUILD_IMAGE: "ubuntu22.04:openjdk17"
          DOCKER_IMAGE_NAME: "{{.GH_REPO}}"
          DOCKER_IMAGE_TAG: "{{.APP_VERSION}}-distroless-java17-debian11"
          DOCKERFILE_NAME: "Dockerfile.distroless-java17-debian11"
          DOCKERFILE_SCANNER: "semgrep"
      - defer:
        task: common:cleanup-workdir

  build-push-docker-image-distroless-multistage:
    cmds:
      - task: common:git-clone
      - task: common:build-push-docker-image
        vars:
          DOCKER_IMAGE_NAME: "{{.GH_REPO}}"
          DOCKER_IMAGE_TAG: "{{.APP_VERSION}}-distroless-java11-debian11-multistage"
          DOCKERFILE_NAME: "Dockerfile.distroless-java11-debian11-multistage"
      - defer:
        task: common:cleanup-workdir
